parameters:
#    tp_admin2.example.class: Tp\Admin2Bundle\Example

services:
#    tp_admin2.example:
#        class: %tp_admin2.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
