<?php

namespace Tp\BlogBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class StaticController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Tp\BlogBundle\Controller\StaticController();
        return $instance;
    }
}
